# Generated by Django 5.2.5 on 2025-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='pending_sync',
            field=models.BooleanField(default=True),
        ),
    ]
