# Generated by Django 5.2.5 on 2025-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_deliveryrequest_pending_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='addresses',
            field=models.ManyToManyField(related_name='delivery_partners', to='apis.address'),
        ),
    ]
