# Generated by Django 5.2.5 on 2025-08-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_deliverypartner_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_partners', to='apis.deliverypartner'),
        ),
    ]
